apiVersion: v1
data:
  filter-k8s-core-data.conf: |
    <filter journal.system.kubernetes.master>
      @type record_transformer
      enable_ruby
      <record>
        k8s_api ${record['MESSAGE'].match(/GET \/api/)[0]}
      </record>
    </filter>
  filter-k8s-core-rewrite.conf: |
    <match journal.systemd**>
      @type rewrite_tag_filter
      rewriterule1 _SYSTEMD_UNIT ^origin-master.service journal.system.kubernetes.master
      rewriterule2 _SYSTEMD_UNIT ^origin-node.service journal.system.kubernetes.node
    </match>
  fluent.conf: |
    # This file is the fluentd configuration entrypoint. Edit with care.
    @include configs.d/openshift/system.conf
    # In each section below, pre- and post- includes don't include anything initially;
    # they exist to enable future additions to openshift conf as needed.
    ## sources
    ## ordered so that syslog always runs last...
    @include configs.d/openshift/input-pre-*.conf
    @include configs.d/dynamic/input-docker-*.conf
    @include configs.d/dynamic/input-syslog-*.conf
    @include configs.d/openshift/input-post-*.conf
    ##
    <label @INGRESS>
    ## filters
      @include configs.d/openshift/filter-pre-*.conf
      @include configs.d/openshift/filter-retag-journal.conf
      @include configs.d/openshift/filter-k8s-meta.conf
      @include configs.d/openshift/filter-kibana-transform.conf
      @include configs.d/openshift/filter-k8s-flatten-hash.conf
      @include configs.d/openshift/filter-k8s-record-transform.conf
      @include configs.d/user/filter-k8s-core-rewrite.conf
      @include configs.d/user/filter-k8s-core-data.conf
      @include configs.d/openshift/filter-syslog-record-transform.conf
      @include configs.d/openshift/filter-viaq-data-model.conf
      @include configs.d/openshift/filter-post-*.conf
    ##
    ## matches
      @include configs.d/openshift/output-pre-*.conf
      @include configs.d/openshift/output-operations.conf
      @include configs.d/openshift/output-applications.conf
      # no post - applications.conf matches everything left
    ##
    </label>
  secure-forward.conf: |
    # @type secure_forward
    # self_hostname ${HOSTNAME}
    # shared_key <SECRET_STRING>
    # secure yes
    # enable_strict_verification yes
    # ca_cert_path /etc/fluent/keys/your_ca_cert
    # ca_private_key_path /etc/fluent/keys/your_private_key
      # for private CA secret key
    # ca_private_key_passphrase passphrase
    # <server>
      # or IP
    #   host server.fqdn.example.com
    #   port 24284
    # </server>
  throttle-config.yaml: |
    # Logging example fluentd throttling config file
    #example-project:
    #  read_lines_limit: 10
    #
    #.operations:
    #  read_lines_limit: 100
kind: ConfigMap
metadata:
  creationTimestamp: 2017-06-22T07:07:01Z
  name: logging-fluentd
  namespace: logging
  resourceVersion: "28178"
  selfLink: /api/v1/namespaces/logging/configmaps/logging-fluentd
uid: 63e54fed-5719-11e7-afcc-5254001d8ce7
